#!/bin/sh
export PATH=/usr/bin:$PATH
. "$(dirname "$0")/_/husky.sh"

# Enable colors
if command -v tty >/dev/null 2>&1; then
  exec >/dev/tty 2>&1
fi

# Check if file is changed
isChanged() {
  git diff --name-only HEAD@{1} HEAD | grep "^$1" >/dev/null 2>&1
}

# Checkout composer.lock or package-lock.json if changed
if isChanged 'composer.lock' || isChanged 'package-lock.json'; then
  git checkout --theirs composer.lock package-lock.json && git add composer.lock package-lock.json
  echo -e "\e[32mFiles <package-lock.json> or <composer.lock> changed.\e[0m"
  echo -e "\e[32mRun composer/npm install to bring your dependencies up to date.\e[0m"
fi
