#!/bin/sh
export PATH=/usr/bin:$PATH
. "$(dirname "$0")/_/husky.sh"

# Enable colors
if [ -t 1 ]; then
    exec >/dev/tty 2>&1
fi

# Check if the current Git command is a rebase
if test "$GIT_COMMAND" = "rebase"; then
    npx chalk-cli --no-stdin -t "{green ✔} Skip pre-commit hook during rebase"
    exit 0
fi

npx git-precommit-checks
npx lint-staged --cwd ${INIT_CWD:-$PWD}
