#!/bin/sh
export PATH=/usr/bin:$PATH
. "$(dirname "$0")/_/husky.sh"

# Enable colors
if command -v tty >/dev/null 2>&1; then
    exec >/dev/tty 2>&1
fi

# Check if the current Git branch name is valid
npx validate-branch-name
