#!/bin/sh
export PATH=/usr/bin:$PATH
. "$(dirname "$0")/_/husky.sh"

# Enable colors
if command -v tty >/dev/null 2>&1; then
  exec >/dev/tty 2>&1
fi

# Edit commit message
if [ $(grep -cv -e '^#' -e '^$' .git/COMMIT_EDITMSG) -eq 0 ]; then
  (exec </dev/tty && npx cz --hook || echo -e "\e[1m\e[31m!\e[0m Unable to start commitizen.") || echo -e "\e[1m\e[31m!\e[0m Commitizen failed."
else
  echo -e "\e[34m→\e[0m Commitizen not relevant. Skipping..."
fi
