#!/bin/sh
export PATH=/usr/bin:$PATH
. "$(dirname "$0")/_/husky.sh"

changed() {
  git diff --name-only HEAD@{1} HEAD | grep "^$1" > /dev/null 2>&1
}

if changed 'composer.lock' || changed 'package-lock.json'
then
  git checkout --theirs composer.lock package-lock.json
  echo "📦 package-lock.json or composer.lock changed. Run npm install to bring your dependencies up to date."
fi
